# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image_path',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dish_images/default.jpg', upload_to='dish_images/'),
        ),
    ]
